  Source.cpp
D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\src\A0102_SDL\Source.cpp(16,1): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\src\A0102_SDL\Source.cpp(16,1): message : __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\src\A0102_SDL\Source.cpp(21,1): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\src\A0102_SDL\Source.cpp(21,1): message : __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\src\A0102_SDL\Source.cpp(26,1): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\src\A0102_SDL\Source.cpp(26,1): message : __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\src\A0102_SDL\Source.cpp(34,1): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\src\A0102_SDL\Source.cpp(34,1): message : __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\src\A0102_SDL\Source.cpp(43,1): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\src\A0102_SDL\Source.cpp(43,1): message : __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
  A0102_SDL.vcxproj -> D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\\bin\Win32Debug\A0102_SDL.exe
  0 archivo(s) copiado(s)
