  Source.cpp
D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\src\A0102_SDL\Source.cpp(19,1): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\src\A0102_SDL\Source.cpp(19,1): message : __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\src\A0102_SDL\Source.cpp(24,1): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\src\A0102_SDL\Source.cpp(24,1): message : __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\src\A0102_SDL\Source.cpp(29,1): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\src\A0102_SDL\Source.cpp(29,1): message : __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\src\A0102_SDL\Source.cpp(37,1): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\src\A0102_SDL\Source.cpp(37,1): message : __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\src\A0102_SDL\Source.cpp(40,1): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\src\A0102_SDL\Source.cpp(40,1): message : __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\src\A0102_SDL\Source.cpp(44,1): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\src\A0102_SDL\Source.cpp(44,1): message : __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\src\A0102_SDL\Source.cpp(49,1): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\src\A0102_SDL\Source.cpp(49,1): message : __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\src\A0102_SDL\Source.cpp(54,1): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\src\A0102_SDL\Source.cpp(54,1): message : __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
  A0102_SDL.vcxproj -> D:\Repos\llenguatjesaplicats2021\llenguatjesAplicats2021\\bin\Win32Debug\A0102_SDL.exe
  0 archivo(s) copiado(s)
